version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build:
        context: .
        dockerfile: docker/Dockerfile
    command: sh -c 'python manage.py collectstatic --noinput && gunicorn --workers=2 --bind=0.0.0.0:8000 covid_stat.wsgi:application'
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    expose: 
      - 8000
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/code/staticfiles
    ports:
      - 8004:80
    depends_on:
      - web

volumes:
  
  static_volume: