# Generated by Django 3.2.3 on 2021-05-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('positive_samples', models.IntegerField(blank=True, null=True)),
                ('negative_samples', models.IntegerField(blank=True, null=True)),
                ('waiting_samples', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NegativeSamples',
        ),
        migrations.DeleteModel(
            name='PositiveSamples',
        ),
        migrations.DeleteModel(
            name='TotalSamples',
        ),
        migrations.DeleteModel(
            name='WaitingSamples',
        ),
    ]
