# Generated by Django 3.2.3 on 2021-05-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20210522_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledetail',
            name='negative_samples_last_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sampledetail',
            name='positive_samples_last_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sampledetail',
            name='total_samples',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sampledetail',
            name='total_samples_last_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
